### ISSUE TITLE
Is possible adding auto copy button ?

### ISSUE THREAD

**Issue by BHXNY** [NthMetal/gbraidfinder#17]
If raids are hot, so I need to copy battle key quickly. But there is no function like auto copy make me annoying.
Could you add that convenient function for raidfinder?

**Comment by NthMetal** [comment]
Yeah I can add this feature today. Should be pretty simple.

I'll close this issue once it's deployed so keep an eye out.

**Comment by NthMetal** [comment]
Fixed with 734d35d61e3ac7e19bc6d071627e805789a00c0a

1. Click the menu for a raid:
![image](https://user-images.githubusercontent.com/7328874/213969391-27e25e5c-3b66-4c43-8888-51eb531826a6.png)
2. Click the auto copy on the bottom:
![image](https://user-images.githubusercontent.com/7328874/213969475-593121ed-9f48-43c3-8630-5a6567391237.png)

Please let me know if there are any issues with this feature!
